project/apps/sensors/models.py
from sqlalchemy import Column, Integer, String, DateTime
from project.database import Base
from project.database import db_session

# FIXME: move to extensions
from flask.ext.sqlalchemy import SQLAlchemy
db = SQLAlchemy()

class Sensor(Base):
    __tablename__ = 'sensors'
    id = Column(Integer, primary_key=True)
    name = Column(String(50), unique=True)
    created_at = Column(DateTime)
    created_by = Column(String(50))
    modified_at = Column(DateTime)
    modified_by = Column(String(50))
    pin = Column(Integer)

    def __init__(self, name=None, created_at=None, created_by=None, modified_at=None ,modified_by=None, pin=None):
        self.name = name
        self.created_at = created_at
        self.created_by = created_by
        self.modified_at = modified_at
        self.modified_by = modified_by
        self.pin = pin

class Log(Base):
    __tablename__ = 'logs'
    id = Column(Integer, primary_key=True)
    sensor_id = Column(Integer, db.ForeignKey('sensors.id'))
    created_at = Column(DateTime)
    change_from = Column(Integer)
    value = Column(Integer)

    # Association
    sensor = db.relationship('Sensor',
      primaryjoin=(sensor_id==Sensor.id),
      backref=db.backref('logs', lazy='dynamic'))
    
    def __init__(self, sensor_id=None, created_at=None, change_from=None, value=None):
        self.sensor_id = sensor_id
        self.created_at = created_at
        self.change_from = change_from
        self.value = value

project/apps/sensors/forms.py
# from python
import re
import urllib

# from wtforms
from wtforms import IntegerField, TextField, PasswordField, BooleanField, TextAreaField
from wtforms.validators import Required, Length, Regexp, Email, optional, EqualTo

# from flask
from flask import g
from flask.ext.wtf import Form
from flaskext.babel import lazy_gettext as _

# from friendfile
# from friendfile.models import Entity


class SensorForm(Form):
    name = TextField('Sensor\'s Name',
                            [Required(message='The name is required')])
    pin = TextField('Sensor\'s Pin Number',
                            [Required(message='a valid PIN number for the sensor is required')])
    def __init__(self, *args, **kwargs):
        Form.__init__(self, *args, **kwargs)

    def validate(self):
        rv = Form.validate(self)
        if not rv:
            return False

project/apps/sensors/views.py
#-*- coding: utf-8 -*-
import re

# flask import
from flask import Blueprint, abort, request, current_app, flash, session, g, redirect, url_for, send_from_directory, make_response, jsonify, render_template
from flask.ext.babel import lazy_gettext as _
from sqlalchemy import desc

#project import
from models import Sensor, Log
from forms import SensorForm
from project.database import db_session

mod = Blueprint('sensors', __name__, url_prefix='/sensors')

@mod.route('/', methods=['GET'])
def index():
    sensor_form = SensorForm()
    sensors = Sensor.query.order_by(desc(Sensor.id)).all()
    return render_template("/sensors/index.html", form=sensor_form, sensors=sensors)

@mod.route('/', methods=['POST'])
def new():
    # TODO: add form vlidation 
    name = request.form.get('name', '')
    pin = request.form.get('pin', '')
    sensor = Sensor(name=name, pin=pin)
    db_session.add(sensor)
    db_session.commit()
    flash(u'successfully created new sensor', 'success')

    return redirect("/sensors/")

@mod.route('/<id>/', methods=['GET'])
def show(id):
    sensor = Sensor.query.filter(Sensor.id == id).first()
    return render_template("/sensors/sensor.html", sensor=sensor)

@mod.route('/<id>/', methods=['POST'])
def update(id):
    # TODO: check if sensor exists
    # TODO: add form vlidation
    sensor = Sensor.query.filter(Sensor.id == id).first()
    
    sensor.name = request.form.get('name', '')
    sensor.pin = request.form.get('pin', '')
    db_session.add(sensor)
    db_session.commit()
    flash(u'successfully updated the sensor', 'success')
    
    return redirect("/sensors")

# FIXME: do it as REST does you idiot!
@mod.route('/<id>/delete', methods=['GET'])
def delete(id):
    # TODO: check if sensor exists
    # TODO: add form vlidation
    sensor = Sensor.query.filter(Sensor.id == id).first()
    
    db_session.delete(sensor)
    db_session.commit()
    flash(u'successfully deleted the sensor', 'success')
    
    return redirect("/sensors")

@mod.route('/<id>/history', methods=['GET'])
def history(id):
    # TODO: check if sensor exists
    # TODO: add form vlidation
    sensor = Sensor.query.filter(Sensor.id == id).first()
    
    return render_template("/sensors/sensor.html", logs=logs, sensor=sensor)

project/templates/sensors/index.html
{% extends 'layout.html' %}
{% block content %}
<div id="page-wrapper">

  <div class="row">
    <div class="col-lg-12">
      <h1>Sensors <small>All Sensors</small></h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"><i class="fa fa-table"></i> Sensors</li>
      </ol>
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
              <div class="alert alert-{{ category }} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
  </div><!-- /.row -->

  <div class="row">
    <div class="col-lg-6">
      <form role="form" method="POST">
        <div class="form-group">
          {{ form.name.label }}
          {{ form.name(size=20, class="form-control", placeholder="Sensor's Name") }}
        </div>
        <div class="form-group">
          {{ form.pin.label }}
          {{ form.pin(size=2, class="form-control", placeholder="Sensor's Pin") }}
        </div>
        <div class="form-group">
          {{ form.csrf_token }}
          <button type="submit" class="btn btn-success">Create New Sensor</button>
        </div>
      </form>
    </div>
    <div class="col-lg-6">
      <h1>Help</h1>
      <p>For complete documentation, please visit <a href="http://getbootstrap.com/css/#forms">Bootstrap's Form Documentation</a>.</p>
    </div>
  </div><!-- /.row -->


  <div class="row">
    <div class="col-lg-12">
      <!--<h2>Bordered Table</h2>-->
      <div class="table-responsive">
        <table class="table table-bordered table-hover tablesorter">
          <thead>
            <tr>
              <th>Row <i class="fa fa-sort"></i></th>
              <th>Name <i class="fa fa-sort"></i></th>
              <th>Pin Number <i class="fa fa-sort"></i></th>
              <th>Status <i class="fa fa-sort"></i></th>
              <th>Created <i class="fa fa-sort"></i></th>
              <th>Modified <i class="fa fa-sort"></i></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for sensor in sensors %}
            <tr>
                <td>{{ sensor.id }}</td>
                <td>{{ sensor.name }}</td>
                <td>{{ sensor.pin }}</td>
                <td>STATUS</td>
                <td>{{ sensor.created_at }}</td>
                <td>{{ sensor.modified_at }}</td>
                <td>
                  <button class="btn btn-link" data-toggle="modal" data-target="#sensorModal{{ loop.index }}">
                    <i class="fa fa-edit"></i> edit
                  </button>
                  <a href="{{ url_for('sensors.delete', id=sensor.id) }}">
                    <i class="fa fa-times"></i> delete
                  </a>
                  <a href="{{ url_for('sensors.history', id=sensor.id) }}">
                    <i class="fa fa-history"></i> view log
                  </a>
                  <!-- Modal -->
                  <div class="modal fade" id="sensorModal{{ loop.index }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <form role="form" method="POST" action="{{ url_for('sensors.update', id=sensor.id) }}">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Sensor's Edit Modal</h4>
                          </div>
                          <div class="modal-body">
                              <div class="form-group">
                                {{ form.name.label }}
                                {{ form.name(value=sensor.name, size=20, class="form-control", placeholder="Sensor's Name") }}
                              </div>
                              <div class="form-group">
                                {{ form.pin.label }}
                                {{ form.pin(value=sensor.pin, size=2, class="form-control", placeholder="Sensor's Pin") }}
                              </div>
                              <div class="form-group">
                                {{ form.csrf_token }}
                              </div>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Edit</button>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                  <!-- /.Modal -->
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.row -->

</div><!-- /#page-wrapper -->
{% endblock %}

project/templates/sensors/sensor.html
{% extends 'layout.html' %}
{% block content %}
<div id="page-wrapper">

  <div class="row">
    <div class="col-lg-12">
      <h1>Sensors <small>History Log</small></h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"><a href="/sensors/"><i class="fa fa-table"></i> Sensors</a></li>
        <li class="active"><i class="fa fa-table"></i> History</li>
      </ol>
      <!--<div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        We're using <a class="alert-link" href="http://tablesorter.com/docs/">Tablesorter 2.0</a> for the sort function on the tables. Read the documentation for more customization options or feel free to use something else!
      </div>-->
    </div>
  </div><!-- /.row -->
  
  <div class="row">
    <div class="col-lg-12">
      <h2>{{ sensor.name }}<br><small>PIN NUMBER {{ sensor.pin }}</small></h2>
      <div class="table-responsive">
        <table class="table table-bordered table-hover tablesorter">
          <thead>
            <tr>
              <th>Row <i class="fa fa-sort"></i></th>
              <th>Current Value <i class="fa fa-sort"></i></th>
              <th>Changed fro value <i class="fa fa-sort"></i></th>
              <th>Created <i class="fa fa-sort"></i></th>
            </tr>
          </thead>
          <tbody>
            {% for log in sensor.logs %}
            <tr>
                <td># {{ loop.index }}</td>
                <td>{{ log.value }}</td>
                <td>{{ log.change_from }}</td>
                <td>{{ log.created_at }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.row -->

</div><!-- /#page-wrapper -->
{% endblock %}