project/apps/sensors/views.py
#-*- coding: utf-8 -*-
import re

# flask import
from flask import Blueprint, abort, request, current_app, flash, session, g, redirect, url_for, send_from_directory, make_response, jsonify, render_template
from flask.ext.babel import lazy_gettext as _
from sqlalchemy import desc

#project import
from models import Sensor, Log
from forms import SensorForm
from project.database import db_session

mod = Blueprint('sensors', __name__, url_prefix='/sensors')

@mod.route('/', methods=['GET'])
def index():
    sensor_form = SensorForm()
    sensors = Sensor.query.order_by(desc(Sensor.id)).all()
    return render_template("/sensors/index.html", form=sensor_form, sensors=sensors)

@mod.route('/', methods=['POST'])
def new():
    # TODO: add form vlidation 
    name = request.form.get('name', '')
    pin = request.form.get('pin', '')
    sensor = Sensor(name=name, pin=pin)
    db_session.add(sensor)
    db_session.commit()
    flash(u'successfully created new sensor', 'success')

    return redirect("/sensors/")

@mod.route('/<id>/', methods=['GET'])
def show(id):
    sensor = Sensor.query.filter(Sensor.id == id).first()
    return render_template("/sensors/sensor.html", sensor=sensor)

@mod.route('/<id>/', methods=['POST'])
def update(id):
    # TODO: check if sensor exists
    # TODO: add form vlidation
    sensor = Sensor.query.filter(Sensor.id == id).first()
    
    sensor.name = request.form.get('name', '')
    sensor.pin = request.form.get('pin', '')
    db_session.add(sensor)
    db_session.commit()
    flash(u'successfully updated the sensor', 'success')
    
    return redirect("/sensors")

# FIXME: do it as REST does you idiot!
@mod.route('/<id>/delete', methods=['GET'])
def delete(id):
    # TODO: check if sensor exists
    # TODO: add form vlidation
    sensor = Sensor.query.filter(Sensor.id == id).first()
    
    db_session.delete(sensor)
    db_session.commit()
    flash(u'successfully deleted the sensor', 'success')
    
    return redirect("/sensors")

@mod.route('/<id>/history', methods=['GET'])
def history(id):
    # TODO: check if sensor exists
    # TODO: add form vlidation
    sensor = Sensor.query.filter(Sensor.id == id).first()
    
    return render_template("/sensors/sensor.html", logs=logs, sensor=sensor)

project/apps/site/views.py
#-*- coding: utf-8 -*-
import re

# flask import
from flask import Blueprint, abort, request, current_app, flash, session, g, redirect, url_for, send_from_directory, make_response, jsonify, render_template
from flask.ext.babel import lazy_gettext as _
from sqlalchemy import desc


#project import
from project.apps.sensors.models import Sensor

mod = Blueprint('site', __name__, url_prefix='/')

@mod.route('/')
def index():
    sensors = Sensor.query.order_by(desc(Sensor.id)).all()
    return render_template("dashboard.html", sensors=sensors)

@mod.route('about/')
def about():
    """
    show Sensor
    """
    return "<center><h1>IRAN‌ PYTHON</h1></center>"

project/templates/dashboard.html
{% extends 'layout.html' %}
{% block content %}
<div id="page-wrapper">

  <div class="row">
    <div class="col-lg-12">
      <h1>Dashboard <small>Statistics Overview</small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
      </ol>
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
              <div class="alert alert-{{ category }} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
              </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
  </div><!-- /.row -->

  <div class="row">
    {% for sensor in sensors %}
    <div class="col-lg-3 sensor" data-sensor-id="{{ sensor.id }}">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-6">
              <i class="fa  fa-bell-o fa-5x"></i>
            </div>
            <div class="col-xs-6 text-right">
              <p class="announcement-heading">{{ sensor.name }}</p>
              <p class="announcement-text">
                {% if sensor.logs.first() %}
                  {{ sensor.logs.first().value }}
                {% else %}
                  unavailable
                {% endif %}
              </p>
            </div>
          </div>
        </div>
        <a href="{{ url_for('sensors.show', id=sensor.id) }}">
          <div class="panel-footer announcement-bottom">
            <div class="row">
              <div class="col-xs-6">
                View More
              </div>
              <div class="col-xs-6 text-right">
                <i class="fa fa-arrow-circle-right"></i>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
    {% endfor %}
  </div><!-- /.row -->
</div><!-- /#page-wrapper -->
{% endblock %}
{% block javascript %}
<script type="text/javascript">
  update = function(){
    $(".sensor").each(function(){
      var sensor_id = $(this).attr('data-sensor-id')
      var that = this
      $.get( "/api/v1/sensor/status/" + sensor_id, function( data ) {
        
        $(that).find(".announcement-text").html(data.value)
        if (data.value == 1){
          $(that).find(".panel").removeClass("panel-info").removeClass("panel-danger").removeClass("panel-success")
          $(that).find(".panel").addClass("panel-success")
        }else{
          $(that).find(".panel").removeClass("panel-info").removeClass("panel-danger").removeClass("panel-success")
          $(that).find(".panel").addClass("panel-danger")
        }
        console.log(data.value)
      });
    })
    setTimeout(update, 2000)
  }
  update()
</script>
{% endblock %}

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">
    

    <!-- Custom Google Web Font -->
    <link href="{{ url_for('static', filename='font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <!--<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>-->

    <!-- Add custom CSS here -->
    <!--<link href="{{ url_for('static', filename='css/bootstrap-rtl.min.css') }}" rel="stylesheet">-->
    <link href="{{ url_for('static', filename='css/sb-admin.css') }}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    
    <div id="wrapper">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">ROI Monitor</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li class=""><a href="{{ url_for('site.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="{{ 'active' if 'sensor' in request.url_rule.rule }}"><a href="{{ url_for('sensors.index') }}"><i class="fa fa-bar-chart-o"></i> Sensors</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
      
      {% block content %}{% endblock %}
      
    </div><!-- /#wrapper -->
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ url_for('static', filename='js/jquery-1.10.2.js') }}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>